//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_LuaNetHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LuaNetHelper");
		L.RegFunction("SendLuaReq", SendLuaReq);
		L.RegFunction("Send2Lua", Send2Lua);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendLuaReq(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			Framework.LuaBuffer arg1 = (Framework.LuaBuffer)ToLua.CheckObject<Framework.LuaBuffer>(L, 2);
			Framework.LuaNetHelper.SendLuaReq(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Send2Lua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			byte[] arg1 = ToLua.CheckByteBuffer(L, 2);
			Framework.LuaNetHelper.Send2Lua(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

