//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_UIModule_LuaUIComWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.UIModule.LuaUICom), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("AddClick", AddClick);
		L.RegFunction("SetSprite", SetSprite);
		L.RegFunction("SetSliderValue", SetSliderValue);
		L.RegFunction("SetGray", SetGray);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("LuaUIPanel", get_LuaUIPanel, set_LuaUIPanel);
		L.RegVar("LuaUITemplate", get_LuaUITemplate, set_LuaUITemplate);
		L.RegVar("LuaUIComName", get_LuaUIComName, set_LuaUIComName);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddClick(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.AddClick");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)ToLua.CheckObject<Framework.UIModule.LuaUICom>(L, 1);
			UnityEngine.Events.UnityAction arg0 = (UnityEngine.Events.UnityAction)ToLua.CheckDelegate<UnityEngine.Events.UnityAction>(L, 2);
			obj.AddClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSprite(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.SetSprite");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)ToLua.CheckObject<Framework.UIModule.LuaUICom>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.SetSprite(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSliderValue(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.SetSliderValue");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)ToLua.CheckObject<Framework.UIModule.LuaUICom>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetSliderValue(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetGray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.SetGray");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)ToLua.CheckObject<Framework.UIModule.LuaUICom>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetGray(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.op_Equality");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaUIPanel(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.LuaUIPanel");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)o;
			Framework.UIModule.LuaUIPanel ret = obj.LuaUIPanel;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUIPanel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaUITemplate(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.LuaUITemplate");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)o;
			Framework.UIModule.LuaUITemplate ret = obj.LuaUITemplate;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUITemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaUIComName(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.LuaUIComName");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)o;
			string ret = obj.LuaUIComName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUIComName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaUIPanel(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.LuaUIPanel");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)o;
			Framework.UIModule.LuaUIPanel arg0 = (Framework.UIModule.LuaUIPanel)ToLua.CheckObject<Framework.UIModule.LuaUIPanel>(L, 2);
			obj.LuaUIPanel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUIPanel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaUITemplate(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.LuaUITemplate");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)o;
			Framework.UIModule.LuaUITemplate arg0 = (Framework.UIModule.LuaUITemplate)ToLua.CheckObject<Framework.UIModule.LuaUITemplate>(L, 2);
			obj.LuaUITemplate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUITemplate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaUIComName(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUICom.LuaUIComName");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUICom obj = (Framework.UIModule.LuaUICom)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.LuaUIComName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUIComName on a nil value");
		}
	}
}

