//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_UIModule_LuaUIPanelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.UIModule.LuaUIPanel), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("LuaUIComArray", get_LuaUIComArray, set_LuaUIComArray);
		L.RegVar("LuaUITemplateArray", get_LuaUITemplateArray, set_LuaUITemplateArray);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUIPanel.op_Equality");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaUIComArray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUIPanel.LuaUIComArray");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUIPanel obj = (Framework.UIModule.LuaUIPanel)o;
			Framework.UIModule.LuaUICom[] ret = obj.LuaUIComArray;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUIComArray on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LuaUITemplateArray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUIPanel.LuaUITemplateArray");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUIPanel obj = (Framework.UIModule.LuaUIPanel)o;
			Framework.UIModule.LuaUITemplate[] ret = obj.LuaUITemplateArray;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUITemplateArray on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaUIComArray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUIPanel.LuaUIComArray");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUIPanel obj = (Framework.UIModule.LuaUIPanel)o;
			Framework.UIModule.LuaUICom[] arg0 = ToLua.CheckObjectArray<Framework.UIModule.LuaUICom>(L, 2);
			obj.LuaUIComArray = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUIComArray on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_LuaUITemplateArray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.UIModule.LuaUIPanel.LuaUITemplateArray");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.UIModule.LuaUIPanel obj = (Framework.UIModule.LuaUIPanel)o;
			Framework.UIModule.LuaUITemplate[] arg0 = ToLua.CheckObjectArray<Framework.UIModule.LuaUITemplate>(L, 2);
			obj.LuaUITemplateArray = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LuaUITemplateArray on a nil value");
		}
	}
}

