//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_LuaUIPanelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.LuaUIPanel), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("luaUIComArray", get_luaUIComArray, set_luaUIComArray);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.LuaUIPanel.op_Equality");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_luaUIComArray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.LuaUIPanel.luaUIComArray");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.LuaUIPanel obj = (Framework.LuaUIPanel)o;
			Framework.LuaUICom[] ret = obj.luaUIComArray;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index luaUIComArray on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_luaUIComArray(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.LuaUIPanel.luaUIComArray");
#endif
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Framework.LuaUIPanel obj = (Framework.LuaUIPanel)o;
			Framework.LuaUICom[] arg0 = ToLua.CheckObjectArray<Framework.LuaUICom>(L, 2);
			obj.luaUIComArray = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index luaUIComArray on a nil value");
		}
	}
}

