//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_Singleton_Framework_LuaUtilityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.Singleton<Framework.LuaUtility>), typeof(System.Object), "Singleton_Framework_LuaUtility");
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Framework.Singleton<Framework.LuaUtility>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

