//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_SingletonInterfaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.SingletonInterface), typeof(System.Object));
		L.RegFunction("Launch", Launch);
		L.RegFunction("SingletonInterfaceOnInitialize", SingletonInterfaceOnInitialize);
		L.RegFunction("SingletonInterfaceOnUninitialize", SingletonInterfaceOnUninitialize);
		L.RegFunction("New", _CreateFramework_SingletonInterface);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFramework_SingletonInterface(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonInterface.ctor");
#endif
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Framework.SingletonInterface obj = new Framework.SingletonInterface();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Framework.SingletonInterface.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Launch(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonInterface.Launch");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Framework.SingletonInterface obj = (Framework.SingletonInterface)ToLua.CheckObject<Framework.SingletonInterface>(L, 1);
			obj.Launch();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SingletonInterfaceOnInitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonInterface.SingletonInterfaceOnInitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Framework.SingletonInterface obj = (Framework.SingletonInterface)ToLua.CheckObject<Framework.SingletonInterface>(L, 1);
			obj.SingletonInterfaceOnInitialize();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SingletonInterfaceOnUninitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonInterface.SingletonInterfaceOnUninitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Framework.SingletonInterface obj = (Framework.SingletonInterface)ToLua.CheckObject<Framework.SingletonInterface>(L, 1);
			obj.SingletonInterfaceOnUninitialize();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

