//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_SingletonBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.SingletonBase), typeof(Framework.Singletoninterface));
		L.RegFunction("Launch", Launch);
		L.RegFunction("OnInitialize", OnInitialize);
		L.RegFunction("OnUninitialize", OnUninitialize);
		L.RegFunction("RegisterOnInitialize", RegisterOnInitialize);
		L.RegFunction("UnRegisterOnInitialize", UnRegisterOnInitialize);
		L.RegFunction("RegisterOnUninitialize", RegisterOnUninitialize);
		L.RegFunction("UnRegisterOnUninitialize", UnRegisterOnUninitialize);
		L.RegFunction("New", _CreateFramework_SingletonBase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFramework_SingletonBase(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.ctor");
#endif
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Framework.SingletonBase obj = new Framework.SingletonBase();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Framework.SingletonBase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Launch(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.Launch");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			obj.Launch();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.OnInitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			obj.OnInitialize();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUninitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.OnUninitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			obj.OnUninitialize();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterOnInitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.RegisterOnInitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			Framework.onInitializeFinishedHandler arg0 = (Framework.onInitializeFinishedHandler)ToLua.CheckDelegate<Framework.onInitializeFinishedHandler>(L, 2);
			obj.RegisterOnInitialize(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegisterOnInitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.UnRegisterOnInitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			Framework.onInitializeFinishedHandler arg0 = (Framework.onInitializeFinishedHandler)ToLua.CheckDelegate<Framework.onInitializeFinishedHandler>(L, 2);
			obj.UnRegisterOnInitialize(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterOnUninitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.RegisterOnUninitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			Framework.onUninitializeStartHandler arg0 = (Framework.onUninitializeStartHandler)ToLua.CheckDelegate<Framework.onUninitializeStartHandler>(L, 2);
			obj.RegisterOnUninitialize(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegisterOnUninitialize(IntPtr L)
	{
#if UNITY_EDITOR
        ToluaProfiler.AddCallRecord("Framework.SingletonBase.UnRegisterOnUninitialize");
#endif
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Framework.SingletonBase obj = (Framework.SingletonBase)ToLua.CheckObject<Framework.SingletonBase>(L, 1);
			Framework.onUninitializeStartHandler arg0 = (Framework.onUninitializeStartHandler)ToLua.CheckDelegate<Framework.onUninitializeStartHandler>(L, 2);
			obj.UnRegisterOnUninitialize(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

