//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_LuaNetUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LuaNetUtil");
		L.RegFunction("SendLuaReq", SendLuaReq);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendLuaReq(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			Framework.LuaBuff arg1 = (Framework.LuaBuff)ToLua.CheckObject<Framework.LuaBuff>(L, 2);
			Framework.LuaNetUtil.SendLuaReq(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

