//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ProtoHelper
{
    private static void RegisterGeneratedProto()
    {
        RegisterProto(typeof(Packet_LoginRequest));
        RegisterProto(typeof(Packet_LoginResponse));
    }
}
