---
---This code was generated by a tool.
---To coding to do what u want to do.
---

module("UI", package.seeall)

LoginData = {}

function LoginData.SerializNetData(msg)
    log("--->>>LoginData SerializNetData.")

end

function LoginData.Clear()
    log("--->>>Clear LoginData.")

end
