---
---This code was generated by a tool.
---To coding to do what u want to do.
---
 
LoginData = {} 
 
function LoginData.SerializNetData(msg)
       log("--->>>LoginData SerializNetData.")
 
end
 
function LoginData.Clear()
       log("--->>>Clear LoginData.")
 
end
