/********************************************************************************
** auth:  https://github.com/HushengStudent
** date:  2018/01/17 23:41:41
** desc:  编辑器扩展
*********************************************************************************/

using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Framework
{
    [CustomEditor(typeof(LuaController))]
    public class LuaControllerEditor : Editor
    {
        private string templateLua =
            "---\r\n" +
            "---This code was generated by a tool.\r\n" +
            "---To coding to do what u want to do.\r\n" +
            "---\r\n" +
            "---\r\n" +
            "ModuleNameCtrl = class(tostring(ModuleNameCtrl), BaseCtrl)\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:ctor()\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:Awake(msg)\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:Start(msg)\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:OnEnable(msg)\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:OnDisable(msg)\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:OnDestroy(msg)\r\n" +
            "end\r\n";


        private string ctrlPath = "C:/Users/husheng/Desktop/MyProject/4GameFramework/myGameFramework/Client/Assets" + "/LuaFramework/Lua/UI/Controller/";
        private string panelPath = "C:/Users/husheng/Desktop/MyProject/4GameFramework/myGameFramework/Client/Assets" + "/LuaFramework/Lua/UI/Data/";
        private string dataPath = "C:/Users/husheng/Desktop/MyProject/4GameFramework/myGameFramework/Client/Assets" + "/LuaFramework/Lua/UI/View/";

        public override void OnInspectorGUI()
        {
            base.DrawDefaultInspector();
            if (GUILayout.Button("create ctrl"))
            {
                LuaController ctrl = target as LuaController;
                if (null == ctrl)
                {
                    LogUtility.PrintError("[LuaControllerEditor]LuaController is null.");
                    return;
                }
                string name = ctrl.gameObject.name;
                string fileName = ctrlPath + name + "Ctrl.lua";
                if (File.Exists(fileName))
                {
                    EditorUtility.DisplayDialog("提示","文件： "+ name + "Ctrl.lua" + " 已存在！", "确认");
                    return;
                }
                TextWriter tw = new StreamWriter(fileName);
                tw.Close();
                string allText = templateLua.Replace("ModuleName", name);
                File.WriteAllText(fileName, allText);
                EditorUtility.DisplayDialog("提示", "文件： " + name + "Ctrl.lua" + " 生成成功！", "确认");
            }
            if (GUILayout.Button("update panel"))
            {

            }
        }
    }
}
