/********************************************************************************
** auth:  https://github.com/HushengStudent
** date:  2018/01/17 23:41:41
** desc:  编辑器扩展
*********************************************************************************/

using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Framework
{
    [CustomEditor(typeof(LuaController))]
    public class LuaControllerEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            base.DrawDefaultInspector();
            if (GUILayout.Button("\r\n" + "更新Prefab信息"))
            {
                LuaController ctrl = target as LuaController;
                if (null == ctrl) return;
                LuaComponent[] componentArray = ctrl.gameObject.GetComponentsInChildren<LuaComponent>();
                for (int i = 0; i < componentArray.Length; i++)
                {
                    if (string.IsNullOrEmpty(componentArray[i].ComponentName))
                    {
                        componentArray[i].ComponentName = componentArray[i].gameObject.name;
                    }
                }
                ctrl.componentArray = new LuaComponent[componentArray.Length];
                for (int i = 0; i < ctrl.componentArray.Length; i++)
                {
                    ctrl.componentArray[i] = componentArray[i];
                }
                AssetDatabase.SaveAssets();
            }
            if (GUILayout.Button("\r\n" + "创建Controller"))
            {
                LuaController ctrl = target as LuaController;
                if (null == ctrl)
                {
                    LogUtility.PrintError("[LuaControllerEditor]LuaController is null.");
                    return;
                }
                string name = ctrl.gameObject.name;
                string fileName = ctrlPath + name + "Ctrl.lua";
                if (File.Exists(fileName))
                {
                    EditorUtility.DisplayDialog("提示", "===>>> 文件： " + name + "Ctrl.lua" + " 已存在！", "确认");
                    return;
                }
                TextWriter tw = new StreamWriter(fileName);
                tw.Close();
                string allText = templateLuaCtrl.Replace("ModuleName", name);
                File.WriteAllText(fileName, allText);
                EditorUtility.DisplayDialog("提示", "===>>> 文件： " + name + "Ctrl.lua" + " 生成成功！", "确认");
            }

            if (GUILayout.Button("\r\n" + "更新 Panel"))
            {

            }

            if (GUILayout.Button("\r\n" + "创建 Data"))
            {

            }
        }

        private string templateLuaCtrl =
            "---\r\n" +
            "---This code was generated by a tool.\r\n" +
            "---To coding to do what u want to do.\r\n" +
            "---\r\n" +
            "module(\"UI\",package.seeall)\r\n" +
            "---\r\n" +
            "ModuleNameCtrl = class(tostring(ModuleNameCtrl), BaseCtrl)\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:ctor()\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:Awake(gameObject)\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:Start()\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:OnEnable()\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:OnDisable()\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNameCtrl:OnDestroy()\r\n" +
            "end\r\n";


        private string templateLuaPanel =
            "---\r\n" +
            "---This code was generated by a tool.\r\n" +
            "---Forbid To coding.\r\n" +
            "---\r\n" +
            "module(\"UI\",package.seeall)\r\n" +
            "---\r\n" +
            "ModuleNamePanel = class(tostring(ModuleNameCtrl))\r\n" +
            "---\r\n" +
            "function ModuleNamePanel:ctor()\r\n" +
            "end\r\n" +
            "---\r\n" +
            "function ModuleNamePanel:BindLuaComponent(gameObject)\r\n" +
            "local l_ctrl = gameObject:GetComponent(\"LuaController\")\r\n" +
            "self.ComponentList = {}\r\n" +
            "#List#"+
            "end\r\n";

        private string luaCom = "self.ComponentList.ComName = l_ctrl.componentArray[i]\r\n";

        private string ctrlPath = "C:/Users/husheng/Desktop/MyProject/4GameFramework/myGameFramework/Client/Assets" + "/LuaFramework/Lua/UI/Controller/";
        private string panelPath = "C:/Users/husheng/Desktop/MyProject/4GameFramework/myGameFramework/Client/Assets" + "/LuaFramework/Lua/UI/Data/";
        private string dataPath = "C:/Users/husheng/Desktop/MyProject/4GameFramework/myGameFramework/Client/Assets" + "/LuaFramework/Lua/UI/View/";
        
        /*
        [InitializeOnLoadMethod]
        static void StartInitializeOnLoadMethod()
        {
            PrefabUtility.prefabInstanceUpdated = delegate (GameObject instance)
            {
                LuaController ctrl = instance.GetComponent<LuaController>();
                if (null == ctrl) return;
                LuaComponent[] componentArray = instance.GetComponentsInChildren<LuaComponent>();
                for (int i = 0; i < componentArray.Length; i++)
                {
                    if (string.IsNullOrEmpty(componentArray[i].ComponentName))
                    {
                        componentArray[i].ComponentName = componentArray[i].gameObject.name;
                    }
                }
                ctrl.componentArray = new LuaComponent[componentArray.Length];
                for (int i = 0; i < ctrl.componentArray.Length; i++)
                {
                    ctrl.componentArray[i] = componentArray[i];
                }
                AssetDatabase.SaveAssets();
            };
        }
        */

    }
}
