---
---This code was generated by a tool.
---To coding to do what u want to do.
---
---
LoginCtrl = class(tostring(LoginCtrl), BaseCtrl)
---
function LoginCtrl:ctor()
end
---
function LoginCtrl:Awake(msg)
end
---
function LoginCtrl:Start(msg)
end
---
function LoginCtrl:OnEnable(msg)
end
---
function LoginCtrl:OnDisable(msg)
end
---
function LoginCtrl:OnDestroy(msg)
end
