---
---This code was generated by a tool.
---To coding to do what u want to do.
---
module("UI",package.seeall)
---
LoginCtrl = class(tostring(LoginCtrl), BaseCtrl)
---
function LoginCtrl:ctor()
end
---
function LoginCtrl:Awake(gameObject)
end
---
function LoginCtrl:Start()
end
---
function LoginCtrl:OnEnable()
end
---
function LoginCtrl:OnDisable()
end
---
function LoginCtrl:OnDestroy()
end
