---
---This code was generated by a tool.
---Forbid To coding.
---

local LoginPanel = class("LoginPanel")

function LoginPanel:ctor()

end

function LoginPanel:BindLuaCom(gameObject)
    local l_ctrl = gameObject:GetComponent("LuaUIPanel")
    self.panel = {}
    self.panel.GameObject = l_ctrl.luaUIComArray[0]
    self.panel.GameObject1 = l_ctrl.luaUIComArray[1]
    self.panel.GameObject2 = l_ctrl.luaUIComArray[2]
    self.panel.GameObject3 = l_ctrl.luaUIComArray[3]
    self.panel.GameObject4 = l_ctrl.luaUIComArray[4]
    self.panel.GameObject5 = l_ctrl.luaUIComArray[5]
    self.panel.GameObject6 = l_ctrl.luaUIComArray[6]
    self.panel.GameObject7 = l_ctrl.luaUIComArray[7]
    self.panel.GameObject8 = l_ctrl.luaUIComArray[8]
    self.panel.GameObject9 = l_ctrl.luaUIComArray[9]

    return self.panel
end

return LoginPanel
